/*
 * generated by Xtext
 */
package org.molymer.conf.ui.contentassist

import org.molymer.conf.ui.contentassist.AbstractConfigDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ConfigDslProposalProvider extends AbstractConfigDslProposalProvider {
}
