/*
 * generated by Xtext
 */
package org.molymer.conf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfigDslUiModule extends org.molymer.conf.ui.AbstractConfigDslUiModule {
	public ConfigDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
