/*
 * generated by Xtext
 */
package org.molymer;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ModelDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.molymer.ui.internal.ModelDslActivator.getInstance().getInjector("org.molymer.ModelDsl");
	}
	
}
