/*
 * generated by Xtext
 */
package org.molymer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModelDslRuntimeModule extends org.molymer.AbstractModelDslRuntimeModule {

}
