/*
 * generated by Xtext
 */
package org.molymer.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModelDslUiModule extends org.molymer.ui.AbstractModelDslUiModule {
	public ModelDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
