/*
 * generated by Xtext
 */
package org.molymer.conf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.molymer.conf.services.ConfigDslGrammarAccess;

public class ConfigDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ConfigDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.molymer.conf.parser.antlr.internal.InternalConfigDslParser createParser(XtextTokenStream stream) {
		return new org.molymer.conf.parser.antlr.internal.InternalConfigDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Config";
	}
	
	public ConfigDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ConfigDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
