/*
 * generated by Xtext
 */
package org.molymer.ui.contentassist

import org.molymer.ui.contentassist.AbstractModelDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ModelDslProposalProvider extends AbstractModelDslProposalProvider {
}
