/*
 * generated by Xtext
 */
package org.molymer.conf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.molymer.conf.ui.internal.ConfigDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfigDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConfigDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConfigDslActivator.getInstance().getInjector(ConfigDslActivator.ORG_MOLYMER_CONF_CONFIGDSL);
	}
	
}
