/*
 * generated by Xtext
 */
package org.molymer.conf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfigDslRuntimeModule extends org.molymer.conf.AbstractConfigDslRuntimeModule {

}
