/*
 * generated by Xtext
 */
package org.molymer.conf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConfigDslStandaloneSetup extends ConfigDslStandaloneSetupGenerated{

	public static void doSetup() {
		new ConfigDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

